reference_jdk: &reference_jdk
                 'JDK="adopt@1.11.28-0"'
reference_os: &reference_os
                'linux'
official_repo: &official_repo
                 'lippo997/Protelis-Demo'
language: bash
git:
  depth: false
os:
  - osx
  - windows
  - *reference_os
dist: xenial
stages:
  - check
  - test
env:
  global:
    - TERM=dumb
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
    - PUBLISH="false"
    - OFFICIAL_REPO_SLUG="lippo997/Protelis-Demo"
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.11.0-3"
    - JDK="adopt@1.12.33-0"
    - JDK="adopt-openj9@1.12.33-0"
matrix:
  exclude:
    - os: *reference_os
      env: *reference_jdk
jobs:
  include:
    - stage: check
      name: "Deep check on reference OS and JDK"
      os: *reference_os
      env:
        - *reference_jdk
      script:
        - cd "$TRAVIS_BUILD_DIR"/alchemist
        - ./gradlew clean check fatJar --scan --parallel
    - stage: deploy
      name: "Reports and deployment"
      if: repo = env(OFFICIAL_REPO_SLUG) AND type != pull_request
      os: *reference_os
      env:
        - PUBLISH="true"
        - *reference_jdk
      install:
        - openssl aes-256-cbc -K $encrypted_9993846e3f84_key -iv $encrypted_9993846e3f84_iv -in prepare_environment.sh.enc -out prepare_environment.sh -d
        - bash prepare_environment.sh
      script:
        - cd "$TRAVIS_BUILD_DIR"/alchemist
        - ./gradlew fatJar dokka buildDashboard projectReport -x test --scan --parallel > >(egrep -v '(null:-1:-1)|(t find node by signature)')
        - mkdir -p report
        - cp --parent */build/reports build/reports report -R
      after_success:
        - ./gradlew orchidDeploy publish --scan --parallel --stacktrace
before_install:
  - curl "${GRAVIS}.disable-windows-defender.sh" --output .disable-windows-defender.sh
  - source .disable-windows-defender.sh
  - curl "${GRAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh
  - source .install-jdk-travis.sh
script:
  - cd "$TRAVIS_BUILD_DIR"/alchemist
  - ./gradlew clean test --scan --parallel
before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - bash .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
